##### Processing arrays: More...


In [1]:
import numpy as np

mx1=np.arange(80).reshape((8,10))

In [2]:
mx1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]])

In [3]:
mx2=np.arange(80).reshape((5,16))
print(mx2)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31]
 [32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47]
 [48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63]
 [64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79]]


In [4]:
# Transpose
mx2.T

array([[ 0, 16, 32, 48, 64],
       [ 1, 17, 33, 49, 65],
       [ 2, 18, 34, 50, 66],
       [ 3, 19, 35, 51, 67],
       [ 4, 20, 36, 52, 68],
       [ 5, 21, 37, 53, 69],
       [ 6, 22, 38, 54, 70],
       [ 7, 23, 39, 55, 71],
       [ 8, 24, 40, 56, 72],
       [ 9, 25, 41, 57, 73],
       [10, 26, 42, 58, 74],
       [11, 27, 43, 59, 75],
       [12, 28, 44, 60, 76],
       [13, 29, 45, 61, 77],
       [14, 30, 46, 62, 78],
       [15, 31, 47, 63, 79]])

In [5]:
#Dot product of two arrays.

m=np.arange(1,5).reshape(2,2)
n=np.arange(2,6).reshape(2,2)
k=np.dot(m,n)
j=np.add(m,n)
print(m,'\n')
print(n,'\n')
print(k,'\n')

print(j)


[[1 2]
 [3 4]] 

[[2 3]
 [4 5]] 

[[10 13]
 [22 29]] 

[[3 5]
 [7 9]]


In [6]:
# create two random arrays that follow a normal distribution

a1=np.random.randn(20).reshape((5,4))
a2=np.random.randn(20).reshape((5,4))
print(a1,a2, sep='\n\n')

[[-0.3753997   0.10754652  0.61538213  0.1752293 ]
 [ 0.06367911  0.11068864 -0.05952282  0.82851349]
 [ 0.45189021 -1.49281776 -0.86044798 -0.01299777]
 [ 0.0517911   0.90067149  0.10957192  0.42984978]
 [ 0.32687056  0.30266236 -0.03021675  0.30328036]]

[[ 0.36472634 -1.6715313  -0.51323117 -0.1531284 ]
 [ 1.04133056 -0.44165097 -0.38171548 -0.93352892]
 [-0.15934533 -1.1350301  -0.63445403 -0.32316811]
 [ 1.20865693  1.36165322  0.60820537  2.23356657]
 [-1.09176387  0.92615192  0.41496511  0.63381563]]


In [7]:
from numpy.random import randn

a3=randn(5,4)
print(a3)

[[ 0.72043597  2.25908912 -0.31905     1.67815513]
 [ 0.38606807  0.5651792  -0.47516146 -0.07584226]
 [-0.91295242 -0.0270247  -0.63326809  0.79510039]
 [ 1.52707884 -0.71380048 -1.04092773  1.33602865]
 [ 1.03015746 -0.60011656  1.30473044 -0.67811389]]


In [8]:
# for more universal functions 
import webbrowser
url = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
webbrowser.open(url)

True

In [9]:
mx1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79]])

In [10]:
np.savetxt('mx_data.txt', mx1, delimiter=',')

In [11]:
mx10=np.loadtxt('mx_data.txt', delimiter=',')
print(mx10)

[[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.]
 [ 10.  11.  12.  13.  14.  15.  16.  17.  18.  19.]
 [ 20.  21.  22.  23.  24.  25.  26.  27.  28.  29.]
 [ 30.  31.  32.  33.  34.  35.  36.  37.  38.  39.]
 [ 40.  41.  42.  43.  44.  45.  46.  47.  48.  49.]
 [ 50.  51.  52.  53.  54.  55.  56.  57.  58.  59.]
 [ 60.  61.  62.  63.  64.  65.  66.  67.  68.  69.]
 [ 70.  71.  72.  73.  74.  75.  76.  77.  78.  79.]]


In [ ]:
# import data from csv files
# you can then manipulate the data

import numpy as np

d1=np.genfromtxt('sample.csv', delimiter=',', names=True)
print(d1,'\n')
#print (d1[9])