__JiaRui Shao__

Assignment 31: numpy ndarrays 

Create two ndarrays of shape (2×2) and fill it with random numbers. Display the two arrays. Calculate and display the dot product of the two arrays. Calculate and display the element-wise sum of the two arrays.


In [18]:
import numpy as np

arr1=np.random.randint(10,size=(2,2))
arr2=np.random.randint(20,size=(2,2))
print(arr1)
print("\n")
print(arr2)
print("\n")

#dot product
dot_p=np.dot(arr1,arr2)
print(dot_p)
print("\n")
ele_add=np.add(arr1,arr2)
print(ele_add)

[[8 0]
 [8 2]]


[[14 10]
 [12  1]]


[[112  80]
 [136  82]]


[[22 10]
 [20  3]]
