#### Data Analysis: Intro to numpy (part1)

##### Agenda
Data Analysis Using Python:<br>
Brief Overview of different packages, Why more packages?<br>
In this module: numpy basics, accessing and processing numpy arrays, and simple matrix operations<br>
(Optional Content) Special Arrays and Scalar Operations <hr>


Why do we need packages like numpy and pandas?  Python is a general purpose language that is flexible.  Using packages like numpy, scipy and pandas allows us to create features that are tailored for data analysis.  for example, list data type in python compared to special purpose data structures such as ndarrays (in numpy) and data frames (in pandas). <br>

Relevant Packages: numpy, scipy, pandas, Matplotlib, seaborn and more<br>
Primary Packages we will use: pandas, numpy, matplotlib <hr>

##### Numpy Basics

In [67]:
# pass a list

import numpy as np

lis=[1,2,3]
arr=np.array(lis)
print(lis)
print(arr)

[1, 2, 3]
[1 2 3]


In [68]:
type(arr)

numpy.ndarray

In [69]:
# accessing elements of the array

print(arr[1])

2


In [70]:
# existing lists -->  multi-dimensional arrays

lis1=[4,5,6]
arr1=np.array(lis1)
mx=np.array([lis,lis1])
print(arr1,'\n')
print(mx)

[4 5 6] 

[[1 2 3]
 [4 5 6]]


In [71]:
type(mx)

numpy.ndarray

In [72]:
mx.dtype

dtype('int32')

In [73]:
mx.shape

(2, 3)

In [74]:
mx[0][0]=10

In [75]:
print (mx)

[[10  2  3]
 [ 4  5  6]]


In [79]:
mx[0][0]='20'


In [81]:
print (mx)
print(mx.dtype)

[[20  2  3]
 [ 4  5  6]]
int32


In [82]:
#Return evenly spaced values within a given interval
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [88]:
np.arange(20,100,5)

array([20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90, 95])

In [83]:
ar1=np.arange(10)
ar2=ar1.astype(np.float64)
print(ar1)
print(ar2)

[0 1 2 3 4 5 6 7 8 9]
[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9.]


In [84]:
ls=[.5,4.6,5.7,6.8,9.9,6.2]
ar1=np.array(ls)
ar2=ar1.astype(np.int32)
print(ar1)
print(ar2)

[ 0.5  4.6  5.7  6.8  9.9  6.2]
[0 4 5 6 9 6]


In [85]:
ar1=np.arange(10)
ar2=np.arange(0,20,2)
print(ar1)
print(ar2)
print(ar1<ar2)


[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]
[False  True  True  True  True  True  True  True  True  True]


In [86]:
myA=np.arange(1000000)
%time for _ in range(10): myA=myA*2
    

Wall time: 24.7 ms


In [87]:
myL=list(range(1000000))
%time for _ in range(10): myL=[x*2 for x in myL]
    

Wall time: 1.71 s


#### Accessing and Processing Numpy Arrays

In [89]:
arr=np.arange(10,55,5)
print(type(arr))
print(arr)

<class 'numpy.ndarray'>
[10 15 20 25 30 35 40 45 50]


In [90]:
# Accessing elements of the array
arr[1]

15

In [91]:
# slicing
arr[:5]

array([10, 15, 20, 25, 30])

In [92]:
# broadcasting: assigning a value with index range

arr[:5]=51
arr

array([51, 51, 51, 51, 51, 35, 40, 45, 50])

In [93]:
# Some subtle points about slicing and copying

arr=np.arange(10,55,5)
arr

array([10, 15, 20, 25, 30, 35, 40, 45, 50])

In [94]:
arr_slice=arr[:5]
arr_slice

array([10, 15, 20, 25, 30])

In [95]:
arr_slice[:5]=12
arr_slice

array([12, 12, 12, 12, 12])

In [96]:
# Will arr be affected?
arr

array([12, 12, 12, 12, 12, 35, 40, 45, 50])

In [ ]:
# Behavior not the same as lists if you use slicing (aliasing). To copy use an explicit method
arr=np.arange(10,55,5)
arr1=arr.copy()
arr1

#### Simple Matrix operations

In [97]:
lis1=[10,15,20]
lis2=[25,30,35]
lis3=[40,45,50]
mx=np.array((lis1, lis2, lis3))

In [98]:
print(mx)

[[10 15 20]
 [25 30 35]
 [40 45 50]]


In [99]:
# Accessing rows

mx[2]

array([40, 45, 50])

In [101]:
# Accessing Individual elements
mx[1][0]
print(mx)

[[10 15 20]
 [25 30 35]
 [40 45 50]]


In [102]:
# 2D array slicing
mx[2,:2]

array([40, 45])

In [104]:
mx[:3,:1]

array([[10],
       [25],
       [40]])

In [103]:
# slice bottom right corner
print(mx)
mx[1:,1:]

[[10 15 20]
 [25 30 35]
 [40 45 50]]


array([[30, 35],
       [45, 50]])


##### Special arrays useful for math and Stats

In [105]:
print(np.zeros((3,3)))

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [ ]:
print(np.ones(2))

In [106]:
print(np.ones((2,2)))

[[ 1.  1.]
 [ 1.  1.]]


In [107]:
print(np.eye(3))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [108]:
print(np.eye(3,4))

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]]


In [109]:
print(np.eye(3,3,1))

[[ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]


<b>Scalar Operations on Arrays</b>

In [1]:
import numpy as np
arr=np.array([1,2,3])
arr1=np.array([4,5,6])
print(arr,arr1)

[1 2 3] [4 5 6]


In [2]:
arr*arr1

array([ 4, 10, 18])

In [3]:
arr+arr1

array([5, 7, 9])

In [4]:
arr-arr1

array([-3, -3, -3])

In [5]:
arr1/arr

array([ 4. ,  2.5,  2. ])