#### pandas - DataFrames

Agenda<br>
Introduction to **DataFrames** - one of the two important data structures in pandas<br>
Working with DataFrames<br>
Importing financial data from sources such as Yahoo Finance<hr>

DataFrame is a very useful data structure in pandas.  <br>
It resembles a spreadsheet full of data with columns describing attributes of the data.  <br>
The first row will contain the column headings; We can optionally explicitly specify an index for each row (see example below), pandas can internally index each row starting from 0.<hr>

In [1]:
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [2]:
tim_gr=[65,80,80]
nanda_gr=[80,80,90]
juan_gr=[90,95,95]

In [3]:
df=DataFrame([tim_gr, nanda_gr, juan_gr], index=['Tim','Nanda','Juan'], columns=['CIS','ACC','MKT'])
print(df)

       CIS  ACC  MKT
Tim     65   80   80
Nanda   80   80   90
Juan    90   95   95


In [4]:
gr_book=np.array([tim_gr, nanda_gr, juan_gr])
print(gr_book)

[[65 80 80]
 [80 80 90]
 [90 95 95]]


In [5]:
df1=DataFrame(gr_book, index=['Tim','Nanda','Juan'],columns=['CIS','ACC','MKT'])
print(df1)

       CIS  ACC  MKT
Tim     65   80   80
Nanda   80   80   90
Juan    90   95   95


In [6]:
# Examining column names

df.columns

Index(['CIS', 'ACC', 'MKT'], dtype='object')

In [7]:
# accessing values in columns

df['CIS']

Tim      65
Nanda    80
Juan     90
Name: CIS, dtype: int64

In [8]:
# accessing rows

#df.head()
#df.tail()
df.head(2)

CIS  ACC  MKT
Tim     65   80   80
Nanda   80   80   90

In [9]:
# accessing rows by index

df.loc[['Tim','Nanda']]

CIS  ACC  MKT
Tim     65   80   80
Nanda   80   80   90

In [10]:
df.iloc[:2]

CIS  ACC  MKT
Tim     65   80   80
Nanda   80   80   90

In [11]:
df.ix[:2,['CIS', 'MKT']]

C:\Users\surface\ananew\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  """Entry point for launching an IPython kernel.


CIS  MKT
Tim     65   80
Nanda   80   90

In [12]:
df[['CIS','MKT']].loc[['Tim','Nanda']]

CIS  MKT
Tim     65   80
Nanda   80   90

In [13]:
df.sum()

CIS    235
ACC    255
MKT    265
dtype: int64

In [14]:
df.describe()

CIS        ACC        MKT
count   3.000000   3.000000   3.000000
mean   78.333333  85.000000  88.333333
std    12.583057   8.660254   7.637626
min    65.000000  80.000000  80.000000
25%    72.500000  80.000000  85.000000
50%    80.000000  80.000000  90.000000
75%    85.000000  87.500000  92.500000
max    90.000000  95.000000  95.000000

In [16]:
import pandas as pd
from pandas import Series,DataFrame
import datetime              
from pandas_datareader import data as wb
import pandas_datareader as pdr

In [17]:
start = datetime.datetime(2016, 1, 1)
end = datetime.datetime(2017, 1, 27)
ticker=['AAPL', 'MSFT', 'AMZN', 'GOOG']

In [50]:
f1=wb.DataReader('AAPL', 'yahoo', start, end)
f2=wb.DataReader('MSFT', 'yahoo', start, end)
f3=wb.DataReader('AMZN', 'yahoo', start, end)
f4=wb.DataReader('GOOG', 'yahoo', start, end)

ImmediateDeprecationError: 
Yahoo Daily has been immediately deprecated due to large breaks in the API without the
introduction of a stable replacement. Pull Requests to re-enable these data
connectors are welcome.

See https://github.com/pydata/pandas-datareader/issues


In [51]:
#Return the first n rows, default n is 5
f1.head()

NameError: name 'f1' is not defined

In [52]:
prices=pd.concat([DataFrame(f1['Close']),DataFrame(f2['Close']),DataFrame(f3['Close']),DataFrame(f4['Close'])],axis=1,join='inner')

NameError: name 'f1' is not defined

In [ ]:
prices.columns=ticker
prices.head()

In [ ]:
prices.loc['2016-01-04']


In [ ]:
%matplotlib inline
prices.plot()

In [ ]:
s = datetime.datetime(2016, 1, 5)
e = datetime.datetime(2016, 2, 5)

f1[s:e]['Open']